/**
 * Admin firma formu — Hizmetler sekmesi: ek uzmanlık (taxonomy) ve ana hizmet checkbox sırası.
 * Veri hâlâ DB’deki slug / main_service_categories adlarıyla saklanır; burada yalnızca panel sırası ve kısa etiket düzeltmeleri.
 */

/** taxonomy.slug — «Ek uzmanlık alanları» bloğu (sıra sabit) */
export const ADMIN_FIRM_SPECIALIZATION_TAXONOMY_SLUG_ORDER: readonly string[] = [
  "golden-visa",
  "yunanistan-golden-visa",
  "kanada-vizesi",
  "ingiltere-vizesi",
  "dubai-vizesi",
  "egitim-vizesi",
  "erasmus-vizesi",
  "yurtdisi-egitim-danismanligi",
  "oturum",
  "vatandaslik",
  "calisma-izni",
  "goc-ve-entegrasyon-danismanligi",
  "nitelikli-isci-gocu",
  "uluslararasi-kariyer-danismanligi",
  "sirket-kurulumu",
  "yatirim-danismanligi",
  "is-gelistirme-danismanligi",
  "is-kurma-danismanligi",
  "hibe-ve-tesvik-danismanligi",
  "hukuki-danismanlik",
  "gocmenlik-hukuku",
  "mesleki-denklik",
  "green-card-basvurulari",
  "turizm-ve-seyahat",
] as const;

/** Checkbox’ta gösterilecek kısa etiket (DB etiketinden farklıysa) */
export const ADMIN_SPECIALIZATION_CHECKBOX_LABEL: Readonly<
  Record<string, string>
> = {
  "yurtdisi-egitim-danismanligi": "Yurtdışı Eğitim",
  "uluslararasi-kariyer-danismanligi": "Uluslararası Kariyer",
  "hukuki-danismanlik": "Hukuki Süreçler",
};

/**
 * main_service_categories.name — «Ana hizmet kategorileri» bloğu (074 ile birebir; yeni satırlar 076 migration).
 */
export const ADMIN_FIRM_MAIN_SERVICE_CATEGORY_ORDER: readonly string[] = [
  "Startup Vizesi",
  "Girişimci Vizesi",
  "Freelancer Vizesi",
  "Sporcu Vizesi",
  "Sanatçı Vizesi",
  "Tır Şoförü Vizesi",
  "Transit Vizesi",
  "Fuar Vizesi",
  "Konferans Vizesi",
  "Ziyaret Vizesi",
  "Diplomatik Vize",
  "E-Vize",
  "Akraba Ziyareti Vizesi",
  "Uzun dönemli / D tipi vizeler",
  "Aile Birleşimi Oturumu",
  "Evlilik Oturumu",
  "Emeklilik Oturumu",
  "Soy Bağları Oturumu",
  "İş/Şirket Temsilcilik Oturumu",
  "Soy Bağı ile Vatandaşlık",
  "Yatırım Yoluyla Vatandaşlık",
  "Yatırım Yoluyla Oturum",
  "Vatandaşlık Hizmetleri",
  "Oturum Hizmetleri",
  "Kültür Turları",
  "Otobüslü Avrupa Turları",
  "Balkan Turları",
  "Gemi Turları",
  "Asya Turları",
  "Vizesiz Turlar",
  "Yurtiçi ve Yurtdışı Tur Programları",
  "Otel Tatilleri",
  "Yurt Dışı Kültür Turları",
  "Yatırım Danışmanlığı",
  "Almanya Eğitim Danışmanlığı",
  "Nitelikli İşçi Yerleştirme",
  "Sağlık Çalışanı Yerleştirme",
  "Sağlık Sektörü İş Yerleştirme",
  "Avukat Desteği",
  "Yeminli Tercüman",
  "Tercüme",
  "Başvuru Süreç Yönetimi",
  "Dosya Hizmeti",
  "Randevu Hizmeti",
  "Konsolosluk İşlemleri",
  "Konsolosluk Yazıları",
  "Ön Onay İşlemleri",
  "Pasaport",
  "Evrak / Danışmanlık",
  "Vize Hizmeti",
  "Konaklama Danışmanlığı",
  "Rezervasyon Hizmeti",
  "Seyahat Sağlık Sigortası",
  "Transfer Hizmetleri",
  "Uçak Bileti",
  "Dil Sınav Merkezi",
  "Dil Sertifikasyon Hizmeti",
  "Uluslararası Kariyer Danışmanlığı",
  "Emlak Danışmanlığı",
  "Kişiye Özel Tatil Hizmetleri",
] as const;
