/**
 * Admin firma formu — Hizmetler sekmesi: ek uzmanlık (taxonomy slug) ve ana hizmet (picklist adı) sırası.
 * Kayıt yine `custom_specialization_slugs` / `main_services` alanlarında; burada yalnızca panelde hangi satırların hangi sırada gösterileceği.
 */

/** «Ek uzmanlık alanları» — yalnızca bu slug sırası (taxonomy) */
export const ADMIN_FIRM_SPECIALIZATION_TAXONOMY_SLUG_ORDER: readonly string[] = [
  "golden-visa",
  "yunanistan-golden-visa",
  "kanada-vizesi",
  "ingiltere-vizesi",
  "dubai-vizesi",
  "yurtdisi-egitim-danismanligi",
  "oturum",
  "vatandaslik",
  "goc-ve-entegrasyon-danismanligi",
  "nitelikli-isci-gocu",
  "uluslararasi-kariyer-danismanligi",
  "sirket-kurulumu",
  "yatirim-danismanligi",
  "is-gelistirme-danismanligi",
  "is-kurma-danismanligi",
  "hibe-ve-tesvik-danismanligi",
  "hukuki-danismanlik",
  "gocmenlik-hukuku",
  "mesleki-denklik",
  "green-card-basvurulari",
  "turizm-ve-seyahat",
  "tur-organizasyonlari",
  "yatirim-yoluyla-vatandaslik",
  "yatirim-yoluyla-oturum",
] as const;

/** Checkbox metni (DB etiketinden farklıysa); (skor) burada ise ayrıca gri «(skor)» etiketi basılmaz */
export const ADMIN_SPECIALIZATION_CHECKBOX_LABEL: Readonly<
  Record<string, string>
> = {
  "yurtdisi-egitim-danismanligi": "Yurtdışı Eğitim",
  "uluslararasi-kariyer-danismanligi": "Uluslararası Kariyer",
  "hukuki-danismanlik": "Hukuki Süreçler",
  "yunanistan-golden-visa": "Yunanistan Golden Visa(skor)",
  "yatirim-danismanligi": "Yatırım Danışmanlığı",
  "is-gelistirme-danismanligi": "İş Geliştirme Danışmanlığı",
  "is-kurma-danismanligi": "İş Kurma Danışmanlığı",
  "tur-organizasyonlari": "Tur Organizasyonları",
};

/**
 * «Ana hizmet kategorileri» — main_service_categories.name sırası (074/076 ile uyumlu yazım).
 */
export const ADMIN_FIRM_MAIN_SERVICE_CATEGORY_ORDER: readonly string[] = [
  "Eğitim Vizesi",
  "Erasmus Vizesi",
  "Çalışma İzni",
  "Startup Vizesi",
  "Girişimci Vizesi",
  "Freelancer Vizesi",
  "Vatandaşlık Hizmetleri",
  "Soy Bağı ile Vatandaşlık",
  "Oturum Hizmetleri",
  "Otobüslü Avrupa Turları",
  "Vizesiz Turlar",
  "Balkan Turları",
  "Gemi Turları",
  "Yurt Dışı Kültür Turları",
  "Otel Tatilleri",
  "Yatırım Danışmanlığı",
  "İş Kurma Danışmanlığı",
  "Transit Vizesi",
  "Fuar Vizesi",
  "Konferans Vizesi",
  "Ziyaret Vizesi",
  "Diplomatik Vize",
  "E-Vize",
  "Sporcu Vizesi",
  "Sanatçı Vizesi",
  "Tır Şoförü Vizesi",
  "Akraba Ziyareti Vizesi",
  "Uzun dönemli / D tipi vizeler",
  "Aile Birleşimi Oturumu",
  "Evlilik Oturumu",
  "Emeklilik Oturumu",
  "Soy Bağları Oturumu",
  "İş/Şirket Temsilcilik Oturumu",
  "Almanya Eğitim Danışmanlığı",
  "Nitelikli İşçi Yerleştirme",
  "Sağlık Çalışanı Yerleştirme",
  "Sağlık Sektörü İş Yerleştirme",
  "Avukat Desteği",
  "Yeminli Tercüman",
  "Tercüme",
  "Kültür Turları",
  "Asya Turları",
  "Yurtiçi ve Yurtdışı Tur Programları",
  "Başvuru Süreç Yönetimi",
  "Dosya Hizmeti",
  "Randevu Hizmeti",
  "Konsolosluk İşlemleri",
  "Konsolosluk Yazıları",
  "Ön Onay İşlemleri",
  "Pasaport",
  "Evrak / Danışmanlık",
  "Vize Hizmeti",
  "Konaklama Danışmanlığı",
  "Rezervasyon Hizmeti",
  "Seyahat Sağlık Sigortası",
  "Transfer Hizmetleri",
  "Uçak Bileti",
  "Dil Sınav Merkezi",
  "Dil Sertifikasyon Hizmeti",
  "Uluslararası Kariyer Danışmanlığı",
  "Emlak Danışmanlığı",
  "Kişiye Özel Tatil Hizmetleri",
  "Gayrimenkul Danışmanlığı",
  "Hukuki Danışmanlık",
  "Turistik Vize",
  "Yatırım Göçü Danışmanlığı",
  "Yurtdışı Eğitim Danışmanlığı",
] as const;
