/**
 * Admin firma formu — Hizmetler sekmesi: ek uzmanlık (taxonomy) ve ana hizmet checkbox sırası.
 * Veri hâlâ DB’deki slug / main_service_categories adlarıyla saklanır; burada yalnızca panel sırası ve kısa etiket düzeltmeleri.
 */

/** taxonomy.slug — kullanıcı tarafından istenen sıra */
export const ADMIN_FIRM_SPECIALIZATION_TAXONOMY_SLUG_ORDER: readonly string[] = [
  "golden-visa",
  "yunanistan-golden-visa",
  "kanada-vizesi",
  "ingiltere-vizesi",
  "dubai-vizesi",
  "egitim-vizesi",
  "erasmus-vizesi",
  "startup-vizesi",
  "girisimci-vizesi",
  "freelancer-vizesi",
  "sporcu-vizesi",
  "sanatci-vizesi",
  "tir-soforu-vizesi",
  "transit-vizesi",
  "fuar-vizesi",
  "konferans-vizesi",
  "ziyaret-vizesi",
  "diplomatik-vize",
  "e-vize",
  "akraba-ziyareti-vizesi",
  "oturum",
  "vatandaslik",
  "calisma-izni",
  "uzun-donemli-d-tipi-vizeler",
  "aile-birlesimi-oturumu",
  "evlilik-oturumu",
  "emeklilik-oturumu",
  "soy-baglari-oturumu",
  "is-sirket-temsilcilik-oturumu",
  "soy-bagi-ile-vatandaslik",
  "yatirim-yoluyla-vatandaslik",
  "yatirim-yoluyla-oturum",
  "yurtdisi-egitim-danismanligi",
  "goc-ve-entegrasyon-danismanligi",
  "nitelikli-isci-gocu",
  "uluslararasi-kariyer-danismanligi",
  "sirket-kurulumu",
  "yatirim-danismanligi",
  "is-gelistirme-danismanligi",
  "is-kurma-danismanligi",
  "hibe-ve-tesvik-danismanligi",
  "hukuki-danismanlik",
  "gocmenlik-hukuku",
  "mesleki-denklik",
  "vatandaslik-hizmetleri",
  "oturum-hizmetleri",
  "yatirim-gocu-danismanligi",
  "green-card-basvurulari",
  "turizm-ve-seyahat",
  "kultur-turlari",
  "otobuslu-avrupa-turlari",
  "balkan-turlari",
  "gemi-turlari",
  "asya-turlari",
  "vizesiz-turlar",
  "yurtici-ve-yurtdisi-tur-programlari",
  "otel-tatilleri",
] as const;

/** Checkbox’ta gösterilecek kısa etiket (DB etiketinden farklıysa) */
export const ADMIN_SPECIALIZATION_CHECKBOX_LABEL: Readonly<
  Record<string, string>
> = {
  "yurtdisi-egitim-danismanligi": "Yurtdışı Eğitim",
  "uluslararasi-kariyer-danismanligi": "Uluslararası Kariyer",
  "hukuki-danismanlik": "Hukuki Süreçler",
};

/** main_service_categories.name — kullanıcı tarafından istenen sıra (074 ile uyumlu tam adlar) */
export const ADMIN_FIRM_MAIN_SERVICE_CATEGORY_ORDER: readonly string[] = [
  "Vize Hizmeti",
  "Başvuru Süreç Yönetimi",
  "Randevu Hizmeti",
  "Konsolosluk İşlemleri",
  "Konsolosluk Yazıları",
  "Dosya Hizmeti",
  "Evrak / Danışmanlık",
  "Ön Onay İşlemleri",
  "Pasaport",
  "Konaklama Danışmanlığı",
  "Rezervasyon Hizmeti",
  "Seyahat Sağlık Sigortası",
  "Transfer Hizmetleri",
  "Uçak Bileti",
  "Dil Sınav Merkezi",
  "Dil Sertifikasyon Hizmeti",
  "Yeminli Tercüman",
  "Tercüme",
  "Avukat Desteği",
  "Sağlık Çalışanı Yerleştirme",
  "Sağlık Sektörü İş Yerleştirme",
  "Nitelikli İşçi Yerleştirme",
  "Uluslararası Kariyer Danışmanlığı",
  "Emlak Danışmanlığı",
  "Kişiye Özel Tatil Hizmetleri",
] as const;
