-- Akilli kesif motorunun kullandigi genis alt tur taksonomisini panelde firma atamalarina ac.
-- Sabit boolean uzmanliklar (Schengen, ABD, ogrenci, calisma vb.) korunur; burada eksik kalan ozel slug'lar eklenir.

insert into public.specialization_taxonomy (slug, label, affects_corporate_score, is_active, sort_order)
values
  ('kanada-vizesi', 'Kanada Vizesi', false, true, 1000),
  ('ingiltere-vizesi', 'İngiltere Vizesi', false, true, 1010),
  ('dubai-vizesi', 'Dubai Vizesi', false, true, 1020),
  ('egitim-vizesi', 'Eğitim Vizesi', false, true, 1030),
  ('erasmus-vizesi', 'Erasmus Vizesi', false, true, 1040),
  ('transit-vizesi', 'Transit Vizesi', false, true, 1050),
  ('fuar-vizesi', 'Fuar Vizesi', false, true, 1060),
  ('konferans-vizesi', 'Konferans Vizesi', false, true, 1070),
  ('ziyaret-vizesi', 'Ziyaret Vizesi', false, true, 1080),
  ('diplomatik-vize', 'Diplomatik Vize', false, true, 1090),
  ('e-vize', 'E-Vize', false, true, 1100),
  ('sporcu-vizesi', 'Sporcu Vizesi', false, true, 1110),
  ('sanatci-vizesi', 'Sanatçı Vizesi', false, true, 1120),
  ('tir-soforu-vizesi', 'Tır Şoförü Vizesi', false, true, 1130),
  ('akraba-ziyareti-vizesi', 'Akraba Ziyareti Vizesi', false, true, 1140),
  ('oturum', 'Oturum', false, true, 2000),
  ('calisma-izni', 'Çalışma İzni', false, true, 2010),
  ('uzun-donemli-d-tipi-vizeler', 'Uzun Dönemli / D Tipi Vizeler', false, true, 2020),
  ('aile-birlesimi-oturumu', 'Aile Birleşimi Oturumu', false, true, 2030),
  ('evlilik-oturumu', 'Evlilik Oturumu', false, true, 2040),
  ('emeklilik-oturumu', 'Emeklilik Oturumu', false, true, 2050),
  ('soy-baglari-oturumu', 'Soy Bağları Oturumu', false, true, 2060),
  ('is-sirket-temsilcilik-oturumu', 'İş / Şirket Temsilcilik Oturumu', false, true, 2070),
  ('oturum-hizmetleri', 'Oturum Hizmetleri', false, true, 2080),
  ('goc-ve-entegrasyon-danismanligi', 'Göç ve Entegrasyon Danışmanlığı', false, true, 2090),
  ('nitelikli-isci-gocu', 'Nitelikli İşçi Göçü', false, true, 2100),
  ('golden-visa', 'Golden Visa', false, true, 3000),
  ('yunanistan-golden-visa', 'Yunanistan Golden Visa', false, true, 3010),
  ('yatirim-yoluyla-vatandaslik', 'Yatırım Yoluyla Vatandaşlık', false, true, 3020),
  ('yatirim-yoluyla-oturum', 'Yatırım Yoluyla Oturum', false, true, 3030),
  ('soy-bagi-ile-vatandaslik', 'Soy Bağı ile Vatandaşlık', false, true, 3040),
  ('vatandaslik-hizmetleri', 'Vatandaşlık Hizmetleri', false, true, 3050),
  ('yurtdisi-egitim-danismanligi', 'Yurtdışı Eğitim Danışmanlığı', false, true, 4000),
  ('almanya-egitim-danismanligi', 'Almanya Eğitim Danışmanlığı', false, true, 4010),
  ('freelancer-vizesi', 'Freelancer Vizesi', false, true, 5000),
  ('startup-vizesi', 'Startup Vizesi', false, true, 5010),
  ('girisimci-vizesi', 'Girişimci Vizesi', false, true, 5020),
  ('nitelikli-isci-yerlestirme', 'Nitelikli İşçi Yerleştirme', false, true, 5030),
  ('saglik-calisani-yerlestirme', 'Sağlık Çalışanı Yerleştirme', false, true, 5040),
  ('saglik-sektoru-is-yerlestirme', 'Sağlık Sektörü İş Yerleştirme', false, true, 5050),
  ('uluslararasi-kariyer-danismanligi', 'Uluslararası Kariyer Danışmanlığı', false, true, 5060),
  ('sirket-kurulumu', 'Şirket Kurulumu', false, true, 6000),
  ('is-kurma-danismanligi', 'İş Kurma Danışmanlığı', false, true, 6010),
  ('is-gelistirme-danismanligi', 'İş Geliştirme Danışmanlığı', false, true, 6020),
  ('yatirim-danismanligi', 'Yatırım Danışmanlığı', false, true, 6030),
  ('hibe-ve-tesvik-danismanligi', 'Hibe ve Teşvik Danışmanlığı', false, true, 6040),
  ('hukuki-danismanlik', 'Hukuki Danışmanlık', false, true, 7000),
  ('gocmenlik-hukuku', 'Göçmenlik Hukuku', false, true, 7010),
  ('avukat-destegi', 'Avukat Desteği', false, true, 7020),
  ('yeminli-tercuman', 'Yeminli Tercüman', false, true, 7030),
  ('tercume', 'Tercüme', false, true, 7040),
  ('mesleki-denklik', 'Mesleki Denklik', false, true, 7050),
  ('otobuslu-avrupa-turlari', 'Otobüslü Avrupa Turları', false, true, 8000),
  ('balkan-turlari', 'Balkan Turları', false, true, 8010),
  ('gemi-turlari', 'Gemi Turları', false, true, 8020),
  ('kultur-turlari', 'Kültür Turları', false, true, 8030),
  ('asya-turlari', 'Asya Turları', false, true, 8040),
  ('vizesiz-turlar', 'Vizesiz Turlar', false, true, 8050),
  ('yurtici-ve-yurtdisi-tur-programlari', 'Yurtiçi ve Yurtdışı Tur Programları', false, true, 8060),
  ('otel-tatilleri', 'Otel Tatilleri', false, true, 8070),
  ('basvuru-surec-yonetimi', 'Başvuru Süreç Yönetimi', false, true, 9000),
  ('dosya-hizmeti', 'Dosya Hizmeti', false, true, 9010),
  ('randevu-hizmeti', 'Randevu Hizmeti', false, true, 9020),
  ('konsolosluk-islemleri', 'Konsolosluk İşlemleri', false, true, 9030),
  ('konsolosluk-yazilari', 'Konsolosluk Yazıları', false, true, 9040),
  ('on-onay-islemleri', 'Ön Onay İşlemleri', false, true, 9050),
  ('pasaport', 'Pasaport', false, true, 9060),
  ('evrak-danismanlik', 'Evrak / Danışmanlık', false, true, 9070)
on conflict do nothing;
