-- Ana hizmet kategorileri: yönetim picklist + firma formu `main_services` ile aynı isim kataloğu.
-- Mevcut satırların adı aynıysa sıra ve aktiflik güncellenir; yeni satırlar eklenir.

insert into public.main_service_categories (name, slug, sort_order, is_active)
values
  ('Vize Hizmeti', 'vize-hizmeti', 10, true),
  ('Oturum', 'oturum', 20, true),
  ('Vatandaşlık', 'vatandaslik', 30, true),
  ('Pasaport', 'pasaport', 40, true),
  ('Evrak / Danışmanlık', 'evrak-danismanlik', 50, true),
  ('Randevu Hizmeti', 'randevu-hizmeti', 60, true),
  ('Tercüme', 'tercume', 70, true),
  ('Uzun dönemli / D tipi vizeler', 'uzun-donemli-d-tipi-vizeler', 80, true),
  ('Yurtdışı Eğitim Danışmanlığı', 'yurtdisi-egitim-danismanligi', 90, true),
  ('Başvuru Süreç Yönetimi', 'basvuru-surec-yonetimi', 100, true),
  ('Kişiye Özel Tatil Hizmetleri', 'kisiye-ozel-tatil-hizmetleri', 110, true),
  ('Konsolosluk İşlemleri', 'konsolosluk-islemleri', 120, true),
  ('Rezervasyon Hizmeti', 'rezervasyon-hizmeti', 130, true),
  ('Konsolosluk Yazıları', 'konsolosluk-yazilari', 140, true),
  ('Dosya Hizmeti', 'dosya-hizmeti', 150, true),
  ('Turistik Vize', 'turistik-vize', 160, true),
  ('Eğitim Vizesi', 'egitim-vizesi', 170, true),
  ('Sporcu Vizesi', 'sporcu-vizesi', 180, true),
  ('Sanatçı Vizesi', 'sanatci-vizesi', 190, true),
  ('Akraba Ziyareti Vizesi', 'akraba-ziyareti-vizesi', 200, true),
  ('Konaklama Danışmanlığı', 'konaklama-danismanligi', 210, true),
  ('Şirket Kurulumu', 'sirket-kurulumu', 220, true),
  ('Hukuki Danışmanlık', 'hukuki-danismanlik', 230, true),
  ('Göçmenlik Hukuku', 'gocmenlik-hukuku', 240, true),
  ('Fuar Vizesi', 'fuar-vizesi', 250, true),
  ('Ziyaret Vizesi', 'ziyaret-vizesi', 260, true),
  ('Konferans Vizesi', 'konferans-vizesi', 270, true),
  ('Transit Vizesi', 'transit-vizesi', 280, true),
  ('E-Vize', 'e-vize', 290, true),
  ('Diplomatik Vize', 'diplomatik-vize', 300, true),
  ('Mesleki Denklik', 'mesleki-denklik', 310, true),
  ('Nitelikli İşçi Yerleştirme', 'nitelikli-isci-yerlestirme', 320, true),
  ('Ön Onay İşlemleri', 'on-onay-islemleri', 330, true),
  ('İngiltere Vizesi', 'ingiltere-vizesi', 340, true),
  ('Sağlık Çalışanı Yerleştirme', 'saglik-calisan-yerlestirme', 350, true),
  ('Nitelikli İşçi Göçü', 'nitelikli-isci-gocu', 360, true),
  ('Sağlık Sektörü İş Yerleştirme', 'saglik-sektoru-is-yerlestirme', 370, true),
  ('Uluslararası Kariyer Danışmanlığı', 'uluslararasi-kariyer-danismanligi', 380, true),
  ('Almanya Eğitim Danışmanlığı', 'almanya-egitim-danismanligi', 390, true),
  ('Göç ve Entegrasyon Danışmanlığı', 'goc-ve-entegrasyon-danismanligi', 400, true),
  ('Dil Sınav Merkezi', 'dil-sinav-merkezi', 410, true),
  ('Dil Sertifikasyon Hizmeti', 'dil-sertifikasyon-hizmeti', 420, true),
  ('Yatırım Göçü Danışmanlığı', 'yatirim-gocu-danismanligi', 430, true),
  ('Gayrimenkul Danışmanlığı', 'gayrimenkul-danismanligi', 440, true),
  ('Green Card Başvuruları', 'green-card-basvurulari', 450, true),
  ('Seyahat Sağlık Sigortası', 'seyahat-saglik-sigortasi', 460, true),
  ('Transfer Hizmetleri', 'transfer-hizmetleri', 470, true),
  ('Uçak Bileti', 'ucak-bileti', 480, true),
  ('Yurtiçi ve Yurtdışı Tur Programları', 'yurtici-ve-yurtdisi-tur-programlari', 490, true),
  ('Erasmus Vizesi', 'erasmus-vizesi', 500, true),
  ('Çalışma İzni', 'calisma-izni', 510, true),
  ('Evlilik Oturumu', 'evlilik-oturumu', 520, true),
  ('Emeklilik Oturumu', 'emeklilik-oturumu', 530, true),
  ('İş/Şirket Temsilcilik Oturumu', 'is-sirket-temsilcilik-oturumu', 540, true),
  ('Aile Birleşimi Oturumu', 'aile-birlesimi-oturumu', 550, true),
  ('Soy Bağları Oturumu', 'soy-baglari-oturumu', 560, true),
  ('Yeminli Tercüman', 'yeminli-tercuman', 570, true),
  ('Avukat Desteği', 'avukat-destegi', 580, true),
  ('Emlak Danışmanlığı', 'emlak-danismanligi', 590, true),
  ('Tır Şoförü Vizesi', 'tir-soforu-vizesi', 600, true),
  ('Kültür Turları', 'kultur-turlari', 610, true),
  ('Otobüslü Avrupa Turları', 'otobuslu-avrupa-turlari', 620, true),
  ('Gemi Turları', 'gemi-turlari', 630, true),
  ('Balkan Turları', 'balkan-turlari', 640, true),
  ('Otel Tatilleri', 'otel-tatilleri', 650, true),
  ('Asya Turları', 'asya-turlari', 660, true)
on conflict (name) do update set
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
